name: github-pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: github-pages
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    container: arcatdmz/texlive
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          path: current-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Outline repository
        uses: actions/checkout@v3
        with:
          repository: tomoto0/Outline
          path: outline-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install LaTeX packages
        run: |
          apt-get update && apt-get install -y texlive-full

      - name: Build PDF file
        run: |
          if [ -d "outline-repo" ]; then
            cd outline-repo
            pdflatex -interaction=nonstopmode Outline.tex
            bibtex Outline  # 参考文献のためにbibtexを実行
            pdflatex -interaction=nonstopmode Outline.tex
            pdflatex -interaction=nonstopmode Outline.tex
            mkdir -p ../current-repo/docs
            cp Outline.pdf ../current-repo/docs/
          else
            echo "Error: outline-repo directory not found."
            exit 1
          fi

      - name: List contents of docs directory
        run: |
          ls -la current-repo/docs

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy PDF to main branch
        run: |
          mkdir -p main-repo/docs
          cp current-repo/docs/Outline.pdf main-repo/docs/

      - name: Commit and push PDF to main branch
        run: |
          cd main-repo
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add docs/Outline.pdf
          git commit -m "Add generated PDF to docs"
          git push origin main

      - name: Check LaTeX log
        if: failure()
        run: |
          if [ -d "outline-repo" ]; then
            cd outline-repo
            cat Outline.log
          fi
