name: github-pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: github-pages
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    container: arcatdmz/texlive
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          path: current-repo

      - name: Checkout Outline repository
        uses: actions/checkout@v3
        with:
          repository: tomoto0/Outline
          path: outline-repo
          token: ${{ secrets.ACTIONS_SECRET_GITHUB_TOKEN }}

      - name: Install LaTeX packages
        run: |
          apt-get update && apt-get install -y texlive-full

      - name: Build PDF file
        run: |
          cd outline-repo
          pdflatex Outline.tex
          pdflatex Outline.tex
          mkdir -p ../current-repo/docs
          cp Outline.pdf ../current-repo/docs/

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./current-repo/docs

      - name: Check LaTeX log
        if: failure()
        run: |
          cd outline-repo
          cat Outline.log
