name: github-pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: github-pages
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト (current repository)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Outlineリポジトリをチェックアウト
        uses: actions/checkout@v3
        with:
          repository: tomoto0/Outline
          path: outline-repo

      - name: LaTeXパッケージをインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          texlive-latex-base \
          texlive-latex-extra \
          texlive-fonts-recommended \
          texlive-bibtex-extra \
          texlive-science \
          texlive-publishers \
          cm-super \
          latexmk

      - name: PDFファイルをビルド
        working-directory: outline-repo
        run: |
          set -e
          # 画像ファイルの存在をチェック
          if [ ! -f "Annual income table.png" ] || [ ! -f "A conceptual model.jpeg" ]; then
            echo "Error: 必要な画像ファイルが存在しません。"
            exit 1
          fi
          # latexmkを使用してドキュメントをコンパイル
          latexmk -pdf -interaction=nonstopmode Outline.tex
          mkdir -p ../docs
          cp Outline.pdf ../docs/

      - name: PDFをmainブランチにコミット＆プッシュ
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add docs/Outline.pdf
          if git diff --staged --quiet; then
            echo "変更はありません。"
          else
            git commit -m "生成されたPDFをdocsに追加"
            git push origin main
          fi

      - name: LaTeXログを確認
        if: always()
        working-directory: outline-repo
        run: |
          if [ -f "Outline.log" ]; then
            echo "===== Outline.log ====="
            cat Outline.log
          fi
