name: github-pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: github-pages
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Checkout Outline repository
        uses: actions/checkout@v3
        with:
          repository: tomoto0/Outline
          path: outline-repo

      - name: Install LaTeX packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          texlive-latex-base \
          texlive-latex-extra \
          texlive-fonts-recommended \
          texlive-bibtex-extra \
          texlive-science \
          texlive-publishers \
          cm-super

      - name: Build PDF file
        working-directory: outline-repo
        run: |
          set -e
          # Check if image files exist
          if [ ! -f "Annual income table.png" ] || [ ! -f "A conceptual model.jpeg" ]; then
            echo "Error: Required image files are missing."
            exit 1
          fi
          # Run LaTeX and BibTeX commands
          pdflatex -interaction=nonstopmode Outline.tex || (cat Outline.log && exit 1)
          bibtex Outline || (cat Outline.blg && exit 1)
          pdflatex -interaction=nonstopmode Outline.tex || (cat Outline.log && exit 1)
          pdflatex -interaction=nonstopmode Outline.tex || (cat Outline.log && exit 1)
          mkdir -p ../docs
          cp Outline.pdf ../docs/

      - name: Commit and push PDF to main branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add docs/Outline.pdf
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add generated PDF to docs"
            git push origin main
          fi

      - name: Check LaTeX log
        if: always()
        working-directory: outline-repo
        run: |
          if [ -f "Outline.log" ]; then
            echo "===== Outline.log ====="
            cat Outline.log
          fi
