name: github-pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: github-pages
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    container: arcatdmz/texlive
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full  # Install full TeX Live distribution
        sudo apt-get install -y texlive-latex-extra  # Additional LaTeX packages
        sudo apt-get install -y texlive-science  # Science-related LaTeX packages including algorithm2e
        
      - name: Build PDF file
        run: latexmk -pdf && latexmk -c && mkdir -p docs && cp *.pdf ./docs/
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_SECRET_GITHUB_TOKEN }}
          publish_dir: ./docs
