name: Convert LaTeX to HTML

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert LaTeX to HTML
        run: |
          pandoc Outline.tex -o outline_temp.html \
            --standalone \
            --mathjax \
            --css=https://latex.vercel.app/style.css \
            --highlight-style=pygments

      - name: Add additional CSS and scripts
        run: |
          cat <<EOF > outline.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Research Outline</title>
            <link rel="stylesheet" href="https://latex.vercel.app/style.css">
            <link rel="stylesheet" href="https://latex.vercel.app/prism/prism.css">
            <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/prismjs/prism.min.js"></script>
          </head>
          <body class="latex-dark-auto">
          EOF
          
          cat outline_temp.html >> outline.html
          
          cat <<EOF >> outline.html
          <script>
            MathJax = {
              tex: {
                inlineMath: [['$', '$'],],
              },
            };
          </script>
          </body>
          </html>
          EOF
          
          rm outline_temp.html

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.ACTIONS_SECRET_GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add outline.html
          git commit -m 'Convert LaTeX to HTML with improved styling'
          git push https://x-access-token:${TOKEN}@github.com/tomoto0/Outline.git
