name: Convert LaTeX to HTML
on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Outline repository
        uses: actions/checkout@v3
        with:
          repository: tomoto0/Outline
          path: Outline

      - name: Checkout tomoto0.github.io repository
        uses: actions/checkout@v3
        with:
          repository: tomoto0/tomoto0.github.io
          path: tomoto0.github.io

      - name: Cache TeX Live packages
        uses: actions/cache@v2
        with:
          path: /usr/share/texlive
          key: ${{ runner.os }}-texlive-${{ hashFiles('**/Outline.tex') }}
          restore-keys: |
            ${{ runner.os }}-texlive-

      - name: Install TeX Live
        if: steps.cache-texlive.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Install additional tools
        run: |
          sudo apt-get install -y pandoc
          sudo apt-get install -y pdf2svg
          sudo apt-get install -y poppler-utils

      - name: Convert complex figures to PDF
        run: |
          cd ./Outline
          # ここで複雑な図表のみを含むLaTeXファイルを指定
          pdflatex -interaction=nonstopmode -halt-on-error complex_figures.tex
        continue-on-error: true

      - name: Extract images from PDF
        run: |
          cd ./Outline
          mkdir -p images
          pdfimages -all complex_figures.pdf images/image

      - name: Convert PDF to SVG
        run: |
          cd ./Outline
          pdf2svg complex_figures.pdf complex_figures.svg all

      - name: Convert LaTeX to HTML
        run: |
          pandoc ./Outline/Outline.tex -o outline_temp.html \
            --standalone \
            --mathjax \
            --css=https://latex.vercel.app/style.css \
            --highlight-style=pygments \
            --lua-filter=./Outline/custom-filter.lua

      - name: Add additional CSS and scripts
        run: |
          title=$(grep -m 1 '\\title{' ./Outline/Outline.tex | sed 's/\\title{$$.*$$}/\1/')
          cat <<EOF > ./tomoto0.github.io/outline.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>$title</title>
            <link rel="stylesheet" href="https://latex.vercel.app/style.css">
            <link rel="stylesheet" href="https://latex.vercel.app/prism/prism.css">
            <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/prismjs/prism.min.js"></script>
            <style>
              .download-container {
                display: flex;
                justify-content: center;
                align-items: center;
                padding: 20px 0;
              }
              .download-button {
                background-color: #f1f1f1;
                color: #000;
                padding: 10px 20px;
                border: none;
                border-radius: 4px;
                cursor: pointer;
                font-size: 16px;
              }
              .download-button:hover {
                background-color: #ddd;
              }
              .svg-figure {
                width: 100%;
                max-width: 800px;
                margin: 20px auto;
              }
            </style>
          </head>
          <body class="latex-dark-auto">
            <h1>$title</h1>
            <div class="download-container">
              <a href="complex_figures.pdf" download>
                <button class="download-button">
                  <i class="fa fa-download"></i> Download PDF
                </button>
              </a>
            </div>
          EOF
          
          # Remove the title from the body and add the rest of the content
          sed '1,/<body/d' outline_temp.html | sed '/<h1 class="title">/,/<\/h1>/d' >> ./tomoto0.github.io/outline.html
          
          # Insert SVG figures
          for svg in ./Outline/*.svg; do
            echo "<div class='svg-figure'>" >> ./tomoto0.github.io/outline.html
            cat "$svg" >> ./tomoto0.github.io/outline.html
            echo "</div>" >> ./tomoto0.github.io/outline.html
          done
          
          cat <<'EOF' >> ./tomoto0.github.io/outline.html
          <script>
            MathJax = {
              tex: {
                inlineMath: [['$', '$'],],
              },
            };
          </script>
          </body>
          </html>
          EOF
          
          rm outline_temp.html

      - name: Copy PDF and images
        run: |
          cp ./Outline/complex_figures.pdf ./tomoto0.github.io/
          cp -r ./Outline/images ./tomoto0.github.io/

      - name: Commit and push changes
        run: |
          cd ./tomoto0.github.io
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add outline.html complex_figures.pdf images
          git commit -m 'Convert LaTeX to HTML with improved styling and figures'
          git push

    env:
      GITHUB_TOKEN: ${{ secrets.PAT_FOR_OUTLINE_REPO }}
